on: 
  push:
  pull_request:

name: check

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: nightly/fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    name: nightly / clippy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: cargo clippy
        uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets

  features:
    runs-on: ubuntu-latest
    name: ubuntu / nightly / features
    steps:
      - name: Checkout  
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install nightly 
        uses: dtolnay/rust-toolchain@nightly
      - name: Install hack
        uses: taiki-e/install-action@cargo-hack
      - name: cargo hack
        run: cargo hack --feature-powerset check
