name: coverage

on: [push, pull_request]
  
jobs:
  codecov:
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

