name: "Dependency Review"
# TODO: change to pull only
on: 
  push:
    branches:
      - 'main'
      - 'crashey-*'
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
